### ISSUE TITLE
Endless redirect issue (inside docker)

### ISSUE THREAD

**Issue by riemers** [hjone72/PlexAuth#13]
So i wanted to go use it in docker, i used an alpine nginx (new enough) and based on that i installed php7 and fpm on top of that. Changed all the config to point to the correct session files, set the correct rights on all the files and changed the configs too.

Url comes in, everything looks fine (log wise) but then it start to create this endless loop where it keeps adding the return url to the url. So this ends up "dying" because of too many redirects.

I turned on debug on the config.ini and E_ALL on php.ini but i could not see much new in the logs. I don't think it is because of docker, since it loads fine. Only thing i can think off is that it uses php7. Since nginx is pretty new in the image with alpine, i only got php7 as an option. 

So questions are really, does it work with php7 or is there a known redirect bug and how can we bump up debug to see more?

Thanks.

p.s. i do intend to opensource the docker container creating (since it did took me some time)

**Comment by hjone72** [comment]
Is the docker somewhere I could see?

It's probably to do with the `session_regenerate_id` I'm doing something wrong there. Try commenting out this line: https://github.com/hjone72/PlexAuth/blob/master/inc/include.php#L20

**Comment by hjone72** [comment]
Could you please try this fork https://github.com/hjone72/PlexAuth/tree/session_regenerate and let me know if that works.

**Comment by riemers** [comment]
Same deal on the different branch and also when i comment out that line in the include file. I'll see if i can upload what i have so far, its like a whole usenet block of things, so have to make sure no credentials and stuff is in there..

**Comment by riemers** [comment]
I hope i removed all the bad things, so here is the setup. Its partially done, need to add reverse entry's for the other containers, but you can basicly do a docker-compose build plexauth && docker-compose up -d plexauth. Only has the sample inc's in there of course but maybe you see something wrong. You can find it here: https://github.com/riemers/usenet-docker-plexauth

**Comment by riemers** [comment]
Will update the setup, still have some quirks , but the other issues are fixed. p.s. i didn't need to comment out that line in the include.php. It just worked for me though, dunno if that is bad? :-)
