### ISSUE TITLE
Incorrect username and password error.

### ISSUE THREAD

**Issue by dtjohnst** [hjone72/PlexAuth#14]
Using the correct username (email address) and password in the input form, I constantly get "incorrect username and password" errors.

I'm running on arch linux with php 5.6 and nginx. I've enabled openssl support for php. My server serves php files just fine. I've made the appropriate changes in my nginx configs as per example 2 (all domains were changed as well as pointing to the correct location of the fpm sock). So far I haven't configured any of my webapps to use authentication, but I put a simple html file that's served from the /content location and it loads just fine if I comment out the "auth_request /auth/;" line in the /content location block in nginx. When I uncomment that line, I get successfully redirected to the authentication page, but after entering my plex email address and password, I get a pop-up saying my username and password are incorrect. I have verified they are correct and work fine on plex.tv. There is nothing in my error logs. After 2 hours, I'm at a loss of where to check next.

**Comment by dtjohnst** [comment]
Is this potentially related to the permissions.json? I know nothing about json and so have made no modifications to that file.

**Comment by hjone72** [comment]
Hi,

Could you confirm that you've entered your Plex username into the config file?
https://github.com/hjone72/PlexAuth/blob/master/inc/sample_config.ini.php#L8

**Comment by dtjohnst** [comment]
Yes. In my /srv/http/plexauth/inc/config.ini/php file, I have tried with both my username and my email in the username field. I have also verified the token is correct and my servername. I've also disabled secure (since I'm using http only currently) and set protocol to "http".

**Comment by hjone72** [comment]
Could you please check your PHP logs to see if PHP is unhappy about anything?

**Comment by dtjohnst** [comment]
No. They indicate nothing. In fact, just to be sure I wiped them and restarted the services and the error logs are empty. The access logs do show activity.

**Comment by hjone72** [comment]
jump over onto this discord chat and I'll see if I can help further.

**Comment by dtjohnst** [comment]
Works fine on a clean install. Must be something in my other nginx or php settings I couldn't find. Thanks for all your help.
