### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by ghost** [hjone72/PlexAuth#7]
Hi there, need some helps pls? Ok got nginx installed all working however the initial login is extremely slow, though it was because it was pulling the library data for the footer but that query is very quick. We will deal with this later.
I have installed the fork for plexpy, when i activate username and password in the plexpy admin section i am prevented from logging back into the server due to plexauth. below is the error i am getting trying to access it from within the portal: I hope you can assist

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Powered by CherryPy 5.1.0

**Comment by ghost** [comment]
I'm pretty new to nginx I think it's my www.conf file route! Also how do I add the link to the invites from nginx I did add it in dynamic-menu.module but I might be wrong. A piece of code should help me quickly for both files to be amended. Database is setup and working :)

**Comment by hjone72** [comment]
> Hi there, need some helps pls?

Sure, lets work through this.

> Ok got nginx installed all working however the initial login is extremely slow.

How slow is extremely slow? 10s 30s 1min?

> I have installed the fork for plexpy, when i activate username and password in the plexpy admin section i am prevented from logging back into the server due to plexauth. below is the error i am getting trying to access it from within the portal: I hope you can assist

In your PlexAuth config file, what is the value of your `session_name`?

When you are sitting on the plexpy error page, could you please open developer tools and have a look at the cookies for the page. Do you see your `session_name` cookie?

> I'm pretty new to nginx I think it's my www.conf file route!

Post the file up to past bin and I can take a look. It's probably something to do with the above though.

> Also how do I add the link to the invites from nginx I did add it in dynamic-menu.module but I might be wrong. A piece of code should help me quickly for both files to be amended. Database is setup and working :)

I'm not really sure what you are trying to do here... If you're trying to add the join and invite pages it is as simple as dropping the files from the other repo into your PlexAuth folder (following the folder structure). You should then be able to access them via this url `secure.yourdomain.com/?page=invite` or `/?page=join`

Let me know how you go 😄

**Comment by ghost** [comment]
http://pastebin.com/feDgGPcz
lets get this working first, i am sure this is where the issues is :)

**Comment by hjone72** [comment]
Your config looks good. What issue do you think is in your config?

**Comment by ghost** [comment]
i PM you my details if you can assist :)

**Comment by hjone72** [comment]
Yeah happy to try. PM me on plex forums?

**Comment by AngryNoodlez** [comment]
Sorry to comment on this old issue, but did you find the fix to this?

I'm having the same problem after upgrading to the PlexAuth fork of PlexPy.

**Comment by hjone72** [comment]
The big two with plexpy are the following two lines:
https://github.com/hjone72/plexpy/blob/PlexAuth/plexpy/webauth.py#L45
https://github.com/hjone72/plexpy/blob/PlexAuth/plexpy/webauth.py#L250

PM me on the plex fourms and we can take a look.
