### ISSUE TITLE
Auth to another web server?

### ISSUE THREAD

**Issue by jneljeff** [hjone72/PlexAuth#9]
I'm having a lot of trouble getting things to load in the body area.  Unless it's super simple to explain a better way, could you tell me what I have to modify to set the main page to another webpage?  I'm really only using this to authenticate my automation tools which will be linked from another hosted site.

**Comment by hjone72** [comment]
The easiest and probably what you're after would be to replace this line https://github.com/hjone72/PlexAuth/blob/master/inc/RememberMe.php#L74 to have a redirect to your site.
`header('Location: '.$otherSiteURL);`

See if that works for you.

**Comment by jneljeff** [comment]
So I replace `require('main.page.php');` with `header('Location: '.$http://my.site.com/index.html);`?  Even though I can enter the direct path into my browser, I get stuck on a blank page.

**Comment by jneljeff** [comment]
Nevermind.  Changed it to `header('Location: http://my.site.com/index.html');` and it worked.  Thanks!
